"""initial identity schema

Revision ID: 20260816_0001
Revises:
Create Date: 2026-08-16 00:01:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260816_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('curated_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_curated_companies_normalized_name')
    )
    op.create_table('curated_investors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_curated_investors_normalized_name')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'complete', 'partial', 'failed')", name='ck_ingestion_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_slug', sa.String(length=32), nullable=False),
    sa.Column('profile_url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_managers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_portfolio_managers_normalized_name')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'content_hash', name='uq_source_documents_source_content_hash')
    )
    op.create_table('source_investors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=256), nullable=False),
    sa.Column('name_raw', sa.String(length=512), nullable=False),
    sa.Column('name_normalized', sa.String(length=512), nullable=False),
    sa.Column('profile_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_key', name='uq_source_investors_source_source_key')
    )
    op.create_table('source_securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=256), nullable=False),
    sa.Column('ticker_raw', sa.String(length=128), nullable=False),
    sa.Column('company_name_raw', sa.String(length=512), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('share_class', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_key', name='uq_source_securities_source_source_key')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('user_link', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_link')
    )
    op.create_table('curated_investor_managers',
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['curated_investors.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['portfolio_managers.id'], ),
    sa.PrimaryKeyConstraint('investor_id', 'manager_id', 'source')
    )
    op.create_table('curated_securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('primary_ticker', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('share_class', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['curated_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investor_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('quarter_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pct_portfolio', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('activity', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.ticker'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investor_id', 'company_id', 'quarter_date', name='uq_holding_investor_company_quarter')
    )
    op.create_table('ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('is_contest_winner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_link'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_entity_id', sa.String(length=36), nullable=True),
    sa.Column('deterministic_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('model_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarantine_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("review_status IN ('open', 'reprocessed', 'rejected', 'accepted')", name='ck_quarantine_records_review_status'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_fetches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_portfolio_managers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_investor_id', sa.String(length=36), nullable=False),
    sa.Column('name_raw', sa.String(length=512), nullable=False),
    sa.Column('name_normalized', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['source_investor_id'], ['source_investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalyst',
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('catalysts', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('idea_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('posted_at', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(length=32000), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curated_holding_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('curated_investor_id', sa.String(length=36), nullable=False),
    sa.Column('curated_security_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.CheckConstraint("event_type IN ('open', 'add', 'reduce', 'hold', 'exit', 'unknown')", name='ck_curated_holding_events_event_type'),
    sa.ForeignKeyConstraint(['curated_investor_id'], ['curated_investors.id'], ),
    sa.ForeignKeyConstraint(['curated_security_id'], ['curated_securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descriptions',
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=128000), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('idea_id')
    )
    op.create_table('identity_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('curated_entity_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=256), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('approve', 'reject', 'defer', 'create_new')", name='ck_identity_decisions_decision'),
    sa.ForeignKeyConstraint(['candidate_id'], ['identity_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance',
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('nextDayOpen', sa.Float(), nullable=False),
    sa.Column('nextDayClose', sa.Float(), nullable=False),
    sa.Column('oneWeekClosePerf', sa.Float(), nullable=True),
    sa.Column('twoWeekClosePerf', sa.Float(), nullable=True),
    sa.Column('oneMonthPerf', sa.Float(), nullable=True),
    sa.Column('threeMonthPerf', sa.Float(), nullable=True),
    sa.Column('sixMonthPerf', sa.Float(), nullable=True),
    sa.Column('oneYearPerf', sa.Float(), nullable=True),
    sa.Column('twoYearPerf', sa.Float(), nullable=True),
    sa.Column('threeYearPerf', sa.Float(), nullable=True),
    sa.Column('fiveYearPerf', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('idea_id')
    )
    op.create_table('photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_holding_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_investor_id', sa.String(length=36), nullable=False),
    sa.Column('source_security_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pct_portfolio', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('source_activity', sa.String(length=32), nullable=True),
    sa.Column('source_observation_key', sa.String(length=512), nullable=False),
    sa.Column('fetch_id', sa.String(length=36), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fetch_id'], ['source_fetches.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_investor_id'], ['source_investors.id'], ),
    sa.ForeignKeyConstraint(['source_security_id'], ['source_securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_observation_key', name='uq_source_holding_snapshots_source_observation_key')
    )
    op.create_table('curated_holding_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('curated_investor_id', sa.String(length=36), nullable=False),
    sa.Column('curated_security_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pct_portfolio', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('source_activity', sa.String(length=32), nullable=True),
    sa.Column('completeness', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['curated_investor_id'], ['curated_investors.id'], ),
    sa.ForeignKeyConstraint(['curated_security_id'], ['curated_securities.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_holding_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_snapshot_id', name='uq_curated_holding_snapshots_source_snapshot')
    )
    op.create_table('investor_aliases',
    sa.Column('source_investor_id', sa.String(length=36), nullable=False),
    sa.Column('curated_investor_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['curated_investor_id'], ['curated_investors.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['identity_decisions.id'], ),
    sa.ForeignKeyConstraint(['source_investor_id'], ['source_investors.id'], ),
    sa.PrimaryKeyConstraint('source_investor_id')
    )
    op.create_table('security_aliases',
    sa.Column('source_security_id', sa.String(length=36), nullable=False),
    sa.Column('curated_security_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['curated_security_id'], ['curated_securities.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['identity_decisions.id'], ),
    sa.ForeignKeyConstraint(['source_security_id'], ['source_securities.id'], ),
    sa.PrimaryKeyConstraint('source_security_id')
    )
    op.create_table('staging_holding_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pct_portfolio', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('identity_status', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_holding_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'source_snapshot_id', name='uq_staging_holding_snapshots_run_source_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_holding_snapshots')
    op.drop_table('security_aliases')
    op.drop_table('investor_aliases')
    op.drop_table('curated_holding_snapshots')
    op.drop_table('source_holding_snapshots')
    op.drop_table('photos')
    op.drop_table('performance')
    op.drop_table('identity_decisions')
    op.drop_table('descriptions')
    op.drop_table('curated_holding_events')
    op.drop_table('comments')
    op.drop_table('catalyst')
    op.drop_table('source_portfolio_managers')
    op.drop_table('source_fetches')
    op.drop_table('quarantine_records')
    op.drop_table('identity_candidates')
    op.drop_table('ideas')
    op.drop_table('holdings')
    op.drop_table('curated_securities')
    op.drop_table('curated_investor_managers')
    op.drop_table('users')
    op.drop_table('source_securities')
    op.drop_table('source_investors')
    op.drop_table('source_documents')
    op.drop_table('portfolio_managers')
    op.drop_table('investors')
    op.drop_table('ingestion_runs')
    op.drop_table('curated_investors')
    op.drop_table('curated_companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
